version: '3.9'

services:
  api:
    container_name: booking_api
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "8083:8080" # The Api image always listens on port 8080 inside the container
    environment:
      - ASPNETCORE_ENVIRONMENT=Production # docker will load appsettings.json -> appsettings.Production.json
      - ConnectionStrings__Default=Server=db;Database=BookingDb;User=sa;Password=Yourpassword123!;TrustServerCertificate=True;
    depends_on:
      - db

  db:
    container_name: booking_sql
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Yourpassword123!
    ports:
      - "1434:1433" # The SQL Server image always listens on port 1433 inside the container
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
